### PR TITLE
[WIP] Tutorial tab

### PR DESCRIPTION
**Pull request by ayanamartins**
First minimally decent version of the "Tutorial" tab.
Includes:
- Three examples
- Graphs and tables for the original and randomized data set

Possible future changes:
- Animate randomized tables by changing cell color
- Less stuff on the interface (?)

### CODE REVIEW

**Comment by piklprado** [comment]
Great! My suggestions:
- To explain what is the statistic of interest in each example.
- Include a counter for the number of randomizations ran by the user and/or the number of randomizations with a more extreme value. Something like "y out of x runs generated a value of the statistc of interest greater (smaller) than the observed " where x and y are updated at each run.
- To include the acceptance region in the histogram of null distribution
- Allow multiple runs in a single mouse click (radio buttom?)

**Comment by ayanamartins** [comment]
Great suggestions!

BTW, I am really confused with the merging process. D: Apparently, something went wrong and I don't know how to fix it...

**Comment by andrechalom** [comment]
Hi!

The problem with merging is that both you, Ale and myself have changed the
same lines of code since the original "baseline", so git does not know
which should be the final result for some lines. I can do this merge by
hand, using the command line. Will try to do so still today ;)

**Comment by ayanamartins** [comment]
Thanks, Chalom

I realize that. However, I couldn't find where I can see the code (side by side?) to merge it manually.

**Comment by andrechalom** [comment]
You can't do that on github, but if you click on the "Use the command line"
link below it gives you instructions on how to do that on the command line.

**Comment by ayanamartins** [comment]
I tried that and now my repository went crazy. The colored symbols are actually blinking! :-O

**Comment by ayanamartins** [comment]
I will try to merge these changes through another pull request

**Pull request closed without merging**
